[features]
seeds = false
skip-lint = false
[programs.localnet]
publed_programs = "E2JpF1p5zAzVYxyEkHkD4tVNMYftueEQB782kBBZCB4Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
